language: python

python:
  - "3.5"
  - "3.6"  
  - "2.7"

install:
  - pip install "tox<2.5"
  - pip install "coveralls>=1.0a"

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . ) -- -a "\"--cov-report term-missing --cov critics\""

after_success:
  - coveralls

deploy:
  provider: script
  script: make travis-build-docker
  on:
    branch: master
